title: Fábio Soares Ribeiro
description: Registro histórico, memórias e legado familiar

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

show_downloads: false

collections_dir: pages
collections:
  pages:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

